const mechanicsList = [
    "Area Control / Area Influence",
    "Auction / Bidding",
    "Card Drafting",
    "Cooperative Game",
    "Deck Building",
    "Dice Rolling",
    "Grid Movement",
    "Hand Management",
    "Hidden Roles",
    "Legacy Game",
    "Memory",
    "Modular Board",
    "Negotiation",
    "Network and Route Building",
    "Pattern Building",
    "Pick-up and Deliver",
    "Point to Point Movement",
    "Push Your Luck",
    "Race",
    "Role Playing",
    "Roll and Move",
    "Set Collection",
    "Simultaneous Action Selection",
    "Storytelling",
    "Take That",
    "Tile Placement",
    "Trading",
    "Trick-taking",
    "Variable Player Powers",
    "Worker Placement"
  ];
  export default mechanicsList;